#%RAML 1.0
---
title: TURBO Dashboard API
baseURI: turbo-dev-app01.pmacs.upenn.edu:8089/
version: 0.0.1

/medications:
  /findOrderNamesFromInputString:
    post: 
	  queryParameters:
	    freeTextSearchTerm: 
	      displayName: searchTerm
	      type: JSON String
	      description: free text with a correctly spelled drug role, drug generic name, or drug brand name
	      examples: {"fullName":"analgesic"}
	      required: true
	      responses:
	        200:
	          body:
	            application/json:
	              example:
	                {
    				  "resultsList": [
    				    "IBUPROFEN 600 MG",
    				    "MOTRIN 600 MG",
    				    "1 PERCOCET TABLET"
    				  ]
    				},
			204:
			  header:
			    message:Your input of "analgesic" returned no matches.
			400: 
			  body:
			    application/json:
	              example:
			        """
		            {
    				  "message": "Unable to parse JSON"
				    }
				    """